name: Deployment

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLIENT: client
  SERVER: server

jobs:
  build-and-push-image-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ${{ env.SERVER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - run: yarn build

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.SERVER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-image-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ${{ env.CLIENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy

      - name: Install dependencies
        run: yarn install

      - run: REACT_APP_INSIGHTS_PROJECT_ID=${{ secrets.REACT_APP_INSIGHTS_PROJECT_ID }} REACT_APP_HOST_BACKEND=${{ secrets.REACT_APP_HOST_BACKEND }} yarn build

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.CLIENT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image-client
      - build-and-push-image-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy stack file to remote
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: docker-compose.yml
          remote: animo-demo/docker-compose.yml
          host: dashboard.dev.animo.id
          username: root
          privateKey: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - name: Deploy to Docker Swarm via SSH action
        uses: appleboy/ssh-action@v1.0.3
        env:
          AGENT_PUBLIC_DID_SEED: ${{ secrets.AGENT_PUBLIC_DID_SEED }}
          AGENT_WALLET_KEY: ${{ secrets.AGENT_WALLET_KEY }}
        with:
          host: dashboard.dev.animo.id
          username: root
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          envs: AGENT_PUBLIC_DID_SEED,AGENT_WALLET_KEY
          script: |
            AGENT_PUBLIC_DID_SEED=${AGENT_PUBLIC_DID_SEED} AGENT_WALLET_KEY=${AGENT_WALLET_KEY} docker stack deploy --compose-file animo-demo/docker-compose.yml demo --with-registry-auth
